-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 01:31:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`mascota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mascota` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mascota` (
  `id_Mascota` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_Mascota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `dni_Cliente` VARCHAR(9) NOT NULL,
  `nombre_Cliente` VARCHAR(15) NOT NULL,
  `apellido cliente` VARCHAR(25) NULL,
  `dir_Cliente` VARCHAR(45) NOT NULL,
  `tlf_Cliente` VARCHAR(45) NOT NULL,
  `mascota_id_Mascota` VARCHAR(15) NOT NULL,
  UNIQUE INDEX `dni_Cliente_UNIQUE` (`dni_Cliente` ASC),
  PRIMARY KEY (`dni_Cliente`, `mascota_id_Mascota`),
  INDEX `fk_cliente_mascota_idx` (`mascota_id_Mascota` ASC),sys_configvariableset_timeset_by

    REFERENCES `mydb`.`mascota` (`id_Mascota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
